# fly.toml app configuration file generated for new-notes-app on 2023-07-05T18:06:08-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "new-notes-app"
primary_region = "eze"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
